import { AlertRule, EnhancedAlert, AlertStats } from "@/types/alerts";

export const mockAlertRules: AlertRule[] = [
  {
    id: "rule-1",
    name: "High Temperature Threshold",
    type: "threshold",
    enabled: true,
    assetIds: ["asset-1", "asset-2"],
    parameters: {
      threshold: 80,
      duration: 5,
      tags: ["temperature", "thermal"],
    },
    actions: ["open-prescription", "notify-teams"],
    suppressionWindow: 30,
    createdAt: new Date("2025-01-15"),
    lastTriggered: new Date("2025-10-27T14:30:00"),
  },
  {
    id: "rule-2",
    name: "Vibration Rate of Change",
    type: "rate-of-change",
    enabled: true,
    assetIds: ["asset-1", "asset-3"],
    parameters: {
      threshold: 2.5,
      duration: 10,
      sensitivity: "high",
      tags: ["vibration", "mechanical"],
    },
    actions: ["create-work-order", "escalate-expert"],
    suppressionWindow: 60,
    createdAt: new Date("2025-02-01"),
    lastTriggered: new Date("2025-10-26T09:15:00"),
  },
  {
    id: "rule-3",
    name: "Multivariate Bearing Health",
    type: "multivariate-anomaly",
    enabled: true,
    assetIds: ["asset-1", "asset-2", "asset-3"],
    parameters: {
      sensitivity: "medium",
      tags: ["bearing", "predictive"],
    },
    actions: ["open-prescription", "trigger-ai-runbook"],
    suppressionWindow: 120,
    createdAt: new Date("2025-03-10"),
    lastTriggered: new Date("2025-10-25T16:45:00"),
  },
  {
    id: "rule-4",
    name: "Energy Consumption Spike",
    type: "energy-exception",
    enabled: true,
    assetIds: ["asset-2", "asset-4"],
    parameters: {
      threshold: 150,
      duration: 15,
      tags: ["energy", "efficiency"],
    },
    actions: ["notify-teams", "trigger-ai-runbook"],
    suppressionWindow: 45,
    createdAt: new Date("2025-04-05"),
  },
  {
    id: "rule-5",
    name: "Shutdown Sequence Pattern",
    type: "sequence-pattern",
    enabled: false,
    assetIds: ["asset-3"],
    parameters: {
      sensitivity: "high",
      tags: ["sequence", "safety"],
    },
    actions: ["escalate-expert", "create-work-order"],
    createdAt: new Date("2025-05-20"),
  },
];

export const mockEnhancedAlerts: EnhancedAlert[] = [
  {
    id: "alert-1",
    assetId: "asset-2",
    assetName: "Compressor Unit #2",
    ruleId: "rule-2",
    ruleName: "Vibration Rate of Change",
    severity: "critical",
    title: "Critical Vibration Spike Detected",
    description: "Vibration increased by 340% in 8 minutes. Bearing failure imminent.",
    timestamp: new Date("2025-10-28T08:15:32"),
    acknowledged: false,
    resolved: false,
    businessImpact: "critical",
    safetyRisk: true,
    tags: ["vibration", "mechanical", "bearing", "urgent"],
    duplicateCount: 3,
    relatedAlerts: ["alert-5", "alert-8"],
    estimatedDowntime: 8,
    estimatedCost: 45000,
    autoRecovery: false,
  },
  {
    id: "alert-2",
    assetId: "asset-3",
    assetName: "CNC Mill #3",
    ruleId: "rule-1",
    ruleName: "High Temperature Threshold",
    severity: "high",
    title: "Motor Temperature Exceeds Safe Limit",
    description: "Motor bearing temperature at 87°C, threshold is 80°C for 12 minutes.",
    timestamp: new Date("2025-10-28T07:45:18"),
    acknowledged: true,
    acknowledgedBy: "John Martinez",
    acknowledgedAt: new Date("2025-10-28T07:50:00"),
    resolved: false,
    businessImpact: "high",
    safetyRisk: false,
    tags: ["temperature", "thermal", "motor"],
    duplicateCount: 1,
    relatedAlerts: [],
    estimatedDowntime: 2,
    estimatedCost: 8500,
    autoRecovery: false,
  },
  {
    id: "alert-3",
    assetId: "asset-4",
    assetName: "Conveyor Belt A",
    ruleId: "rule-4",
    ruleName: "Energy Consumption Spike",
    severity: "medium",
    title: "Abnormal Power Draw Detected",
    description: "Energy consumption 35% above baseline. Possible belt tension issue.",
    timestamp: new Date("2025-10-28T06:30:45"),
    acknowledged: true,
    acknowledgedBy: "Sarah Chen",
    acknowledgedAt: new Date("2025-10-28T06:35:00"),
    resolved: true,
    resolvedAt: new Date("2025-10-28T07:15:00"),
    businessImpact: "medium",
    safetyRisk: false,
    tags: ["energy", "efficiency", "belt"],
    duplicateCount: 0,
    relatedAlerts: [],
    estimatedDowntime: 0.5,
    estimatedCost: 1200,
    autoRecovery: true,
  },
  {
    id: "alert-4",
    assetId: "asset-1",
    assetName: "Hydraulic Press #1",
    ruleId: "rule-3",
    ruleName: "Multivariate Bearing Health",
    severity: "high",
    title: "Bearing Degradation Pattern Detected",
    description: "ML model detects early bearing failure signatures. RUL: 45 days.",
    timestamp: new Date("2025-10-28T05:20:12"),
    acknowledged: true,
    acknowledgedBy: "Mike Thompson",
    acknowledgedAt: new Date("2025-10-28T05:25:00"),
    resolved: false,
    businessImpact: "high",
    safetyRisk: false,
    tags: ["bearing", "predictive", "ml"],
    duplicateCount: 0,
    relatedAlerts: ["alert-7"],
    estimatedDowntime: 4,
    estimatedCost: 12000,
    autoRecovery: false,
  },
  {
    id: "alert-5",
    assetId: "asset-2",
    assetName: "Compressor Unit #2",
    ruleId: "rule-1",
    ruleName: "High Temperature Threshold",
    severity: "critical",
    title: "Cooling System Failure",
    description: "Coolant temperature at 95°C. Immediate shutdown recommended.",
    timestamp: new Date("2025-10-28T08:10:05"),
    acknowledged: false,
    resolved: false,
    businessImpact: "critical",
    safetyRisk: true,
    tags: ["temperature", "cooling", "safety", "urgent"],
    duplicateCount: 2,
    relatedAlerts: ["alert-1"],
    estimatedDowntime: 12,
    estimatedCost: 65000,
    autoRecovery: false,
  },
  {
    id: "alert-6",
    assetId: "asset-5",
    assetName: "Paint Booth #1",
    ruleId: "rule-4",
    ruleName: "Energy Consumption Spike",
    severity: "low",
    title: "HVAC Energy Inefficiency",
    description: "HVAC system drawing 15% more power than expected.",
    timestamp: new Date("2025-10-27T22:40:33"),
    acknowledged: true,
    acknowledgedBy: "David Wilson",
    acknowledgedAt: new Date("2025-10-28T06:00:00"),
    resolved: true,
    resolvedAt: new Date("2025-10-28T07:30:00"),
    businessImpact: "low",
    safetyRisk: false,
    tags: ["energy", "hvac", "efficiency"],
    duplicateCount: 0,
    relatedAlerts: [],
    estimatedCost: 450,
    autoRecovery: true,
  },
];

export const mockAlertStats: AlertStats = {
  total: 24,
  acknowledged: 18,
  unacknowledged: 6,
  critical: 3,
  high: 7,
  medium: 9,
  low: 5,
  avgResponseTime: 12.5,
  avgResolutionTime: 145,
};
