import {
  ComponentHealth,
  BOMItem,
  WorkOrder,
  OperatorNote,
  FailurePattern,
  RULForecast,
  PrescriptiveInsight,
  RiskFeature,
} from "@/types/assetDetail";

export const mockComponentHealth: ComponentHealth[] = [
  {
    id: "comp-1",
    name: "Motor Bearings",
    type: "Bearing",
    healthScore: 72,
    confidence: 89,
    status: "warning",
    lastInspection: new Date("2025-10-20"),
    nextInspection: new Date("2025-11-15"),
    sensors: ["vibration-sensor-1", "temp-sensor-2"],
  },
  {
    id: "comp-2",
    name: "Drive Belt",
    type: "Belt",
    healthScore: 91,
    confidence: 95,
    status: "healthy",
    lastInspection: new Date("2025-10-25"),
    nextInspection: new Date("2025-12-01"),
    sensors: ["tension-sensor-1"],
  },
  {
    id: "comp-3",
    name: "Cooling Fan",
    type: "Fan",
    healthScore: 45,
    confidence: 82,
    status: "critical",
    lastInspection: new Date("2025-10-15"),
    nextInspection: new Date("2025-11-01"),
    sensors: ["vibration-sensor-2", "acoustic-sensor-1"],
  },
  {
    id: "comp-4",
    name: "Hydraulic Pump",
    type: "Pump",
    healthScore: 88,
    confidence: 91,
    status: "healthy",
    lastInspection: new Date("2025-10-22"),
    nextInspection: new Date("2025-11-20"),
    sensors: ["pressure-sensor-1", "flow-sensor-1"],
  },
];

export const mockBOM: BOMItem[] = [
  {
    id: "bom-1",
    partNumber: "BRG-6205-2RS",
    description: "Deep Groove Ball Bearing",
    quantity: 2,
    supplier: "SKF Industries",
    leadTime: 5,
    cost: 45.99,
    inStock: true,
  },
  {
    id: "bom-2",
    partNumber: "BELT-A-48",
    description: "V-Belt Type A, 48 inch",
    quantity: 1,
    supplier: "Gates Corporation",
    leadTime: 3,
    cost: 28.50,
    inStock: true,
  },
  {
    id: "bom-3",
    partNumber: "FAN-AC-12",
    description: "Axial Cooling Fan 12V",
    quantity: 1,
    supplier: "Ebm-papst",
    leadTime: 7,
    cost: 156.00,
    inStock: false,
  },
  {
    id: "bom-4",
    partNumber: "PUMP-HYD-250",
    description: "Hydraulic Gear Pump 250cc",
    quantity: 1,
    supplier: "Parker Hannifin",
    leadTime: 14,
    cost: 890.00,
    inStock: false,
  },
];

export const mockWorkOrders: WorkOrder[] = [
  {
    id: "wo-1",
    type: "predictive",
    status: "open",
    priority: "high",
    title: "Replace Motor Bearings",
    description: "Predictive model indicates bearing wear. Replace before failure.",
    assignee: "John Martinez",
    createdAt: new Date("2025-10-26"),
    estimatedHours: 4,
    parts: ["BRG-6205-2RS"],
    cost: 91.98,
    notes: "Schedule during next maintenance window",
  },
  {
    id: "wo-2",
    type: "preventive",
    status: "completed",
    priority: "medium",
    title: "Quarterly Lubrication",
    description: "Standard quarterly maintenance lubrication",
    assignee: "Sarah Chen",
    createdAt: new Date("2025-10-15"),
    completedAt: new Date("2025-10-16"),
    estimatedHours: 1,
    actualHours: 0.8,
    parts: [],
    cost: 25.00,
    notes: "All lubrication points serviced. No issues found.",
  },
  {
    id: "wo-3",
    type: "corrective",
    status: "in-progress",
    priority: "critical",
    title: "Replace Cooling Fan",
    description: "Fan vibration exceeds threshold. Immediate replacement required.",
    assignee: "Mike Thompson",
    createdAt: new Date("2025-10-27"),
    estimatedHours: 2,
    parts: ["FAN-AC-12"],
    cost: 156.00,
    notes: "Ordered replacement part. ETA 3 days.",
  },
];

export const mockOperatorNotes: OperatorNote[] = [
  {
    id: "note-1",
    author: "David Wilson",
    timestamp: new Date("2025-10-27T14:30:00"),
    content: "Noticed unusual noise from cooling fan during afternoon shift. Reported to maintenance.",
    category: "issue",
  },
  {
    id: "note-2",
    author: "Sarah Chen",
    timestamp: new Date("2025-10-26T09:15:00"),
    content: "Completed routine inspection. Motor temperature within normal range.",
    category: "observation",
  },
  {
    id: "note-3",
    author: "John Martinez",
    timestamp: new Date("2025-10-25T16:45:00"),
    content: "Applied temporary fix to cooling fan mounting. Scheduled for replacement.",
    category: "fix",
  },
];

export const mockFailurePatterns: FailurePattern[] = [
  {
    id: "pattern-1",
    name: "Bearing Wear Pattern Alpha",
    matchConfidence: 87,
    symptoms: [
      "Elevated vibration at bearing frequency",
      "Gradual temperature increase",
      "High-frequency acoustic signature",
    ],
    rootCauses: [
      "Insufficient lubrication",
      "Contamination in bearing housing",
      "Excessive load conditions",
    ],
    historicalOccurrences: 12,
    lastOccurrence: new Date("2025-08-15"),
  },
  {
    id: "pattern-2",
    name: "Fan Imbalance Signature",
    matchConfidence: 94,
    symptoms: [
      "1X RPM vibration spike",
      "Unstable amplitude",
      "Bearing stress indicators",
    ],
    rootCauses: ["Fan blade damage", "Mounting looseness", "Accumulated debris"],
    historicalOccurrences: 8,
    lastOccurrence: new Date("2025-09-22"),
  },
];

export const mockRULForecast: RULForecast = {
  daysRemaining: 45,
  confidence: 78,
  confidenceBands: {
    lower: 32,
    upper: 58,
  },
  failureProbability: [
    { day: 0, probability: 2 },
    { day: 7, probability: 5 },
    { day: 14, probability: 10 },
    { day: 21, probability: 18 },
    { day: 28, probability: 28 },
    { day: 35, probability: 42 },
    { day: 42, probability: 58 },
    { day: 49, probability: 72 },
    { day: 56, probability: 84 },
    { day: 63, probability: 92 },
  ],
};

export const mockPrescriptiveInsights: PrescriptiveInsight[] = [
  {
    id: "insight-1",
    priority: "high",
    rootCause: "Motor bearing degradation due to inadequate lubrication frequency",
    confidence: 87,
    recommendedActions: [
      {
        action: "Replace motor bearings (both)",
        impact: "Prevents catastrophic failure, extends motor life by 2-3 years",
        effort: "4 hours, 2 technicians",
        requiredParts: ["BRG-6205-2RS (qty: 2)"],
        estimatedDowntime: "4-6 hours",
        safetyNotes: [
          "Lockout/tagout required",
          "Ensure motor is completely de-energized",
          "Wear safety glasses and gloves",
        ],
      },
      {
        action: "Increase lubrication frequency to every 2 months",
        impact: "Reduces future bearing wear by 40%",
        effort: "15 minutes, 1 technician",
        requiredParts: ["High-temp bearing grease"],
        estimatedDowntime: "None (can be done during operation)",
        safetyNotes: ["Standard PPE required"],
      },
    ],
    estimatedSavings: 3500,
    riskIfIgnored: "75% probability of complete bearing failure within 45 days, leading to motor damage ($8,000+) and 2-3 days unplanned downtime",
  },
  {
    id: "insight-2",
    priority: "critical",
    rootCause: "Cooling fan imbalance causing excessive vibration and bearing stress",
    confidence: 94,
    recommendedActions: [
      {
        action: "Replace cooling fan assembly",
        impact: "Eliminates vibration, prevents bearing damage",
        effort: "2 hours, 1 technician",
        requiredParts: ["FAN-AC-12"],
        estimatedDowntime: "2-3 hours",
        safetyNotes: [
          "De-energize fan circuit",
          "Allow fan to come to complete stop",
          "Wear cut-resistant gloves",
        ],
      },
    ],
    estimatedSavings: 1200,
    riskIfIgnored: "Fan failure imminent (7-10 days), will cause overheating and potential motor damage",
  },
];

export const mockRiskFeatures: RiskFeature[] = [
  {
    feature: "Bearing Temperature",
    importance: 0.92,
    currentValue: 78.5,
    normalRange: "45-65°C",
    contribution: "negative",
  },
  {
    feature: "Vibration RMS",
    importance: 0.88,
    currentValue: 12.3,
    normalRange: "2-8 mm/s",
    contribution: "negative",
  },
  {
    feature: "High Frequency Peaks",
    importance: 0.76,
    currentValue: 8.7,
    normalRange: "0-4 g",
    contribution: "negative",
  },
  {
    feature: "Load Factor",
    importance: 0.64,
    currentValue: 0.82,
    normalRange: "0.6-0.85",
    contribution: "negative",
  },
  {
    feature: "Operating Hours Since Maintenance",
    importance: 0.58,
    currentValue: 2240,
    normalRange: "0-2000 hrs",
    contribution: "negative",
  },
];
