import { Asset, Alert, KPI } from '@/types/asset';

export const mockAssets: Asset[] = [
  {
    id: 'asset-1',
    name: 'Hydraulic Press #1',
    type: 'Press',
    status: 'healthy',
    healthScore: 94,
    location: { x: -15, y: 0, z: -10 },
    temperature: 68,
    vibration: 0.8,
    pressure: 145,
    lastMaintenance: new Date('2024-09-15'),
    nextMaintenance: new Date('2025-01-15'),
    alerts: 0,
  },
  {
    id: 'asset-2',
    name: 'CNC Mill #3',
    type: 'Mill',
    status: 'warning',
    healthScore: 72,
    location: { x: 0, y: 0, z: -10 },
    temperature: 82,
    vibration: 2.4,
    pressure: 120,
    lastMaintenance: new Date('2024-08-20'),
    nextMaintenance: new Date('2024-12-20'),
    alerts: 3,
  },
  {
    id: 'asset-3',
    name: 'Conveyor Belt A',
    type: 'Conveyor',
    status: 'healthy',
    healthScore: 88,
    location: { x: 15, y: 0, z: -10 },
    temperature: 55,
    vibration: 1.2,
    pressure: 0,
    lastMaintenance: new Date('2024-10-01'),
    nextMaintenance: new Date('2025-02-01'),
    alerts: 0,
  },
  {
    id: 'asset-4',
    name: 'Compressor Unit #2',
    type: 'Compressor',
    status: 'critical',
    healthScore: 45,
    location: { x: -15, y: 0, z: 10 },
    temperature: 105,
    vibration: 4.8,
    pressure: 180,
    lastMaintenance: new Date('2024-06-10'),
    nextMaintenance: new Date('2024-11-10'),
    alerts: 7,
  },
  {
    id: 'asset-5',
    name: 'Welding Robot #5',
    type: 'Robot',
    status: 'healthy',
    healthScore: 96,
    location: { x: 0, y: 0, z: 10 },
    temperature: 62,
    vibration: 0.5,
    pressure: 0,
    lastMaintenance: new Date('2024-10-10'),
    nextMaintenance: new Date('2025-03-10'),
    alerts: 0,
  },
  {
    id: 'asset-6',
    name: 'Paint Booth #1',
    type: 'Booth',
    status: 'offline',
    healthScore: 0,
    location: { x: 15, y: 0, z: 10 },
    temperature: 0,
    vibration: 0,
    pressure: 0,
    lastMaintenance: new Date('2024-09-25'),
    nextMaintenance: new Date('2025-01-25'),
    alerts: 1,
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 'alert-1',
    assetId: 'asset-4',
    assetName: 'Compressor Unit #2',
    severity: 'critical',
    title: 'Temperature Exceeding Safe Limits',
    description: 'Operating temperature at 105°C, above threshold of 95°C. Immediate inspection required.',
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    acknowledged: false,
  },
  {
    id: 'alert-2',
    assetId: 'asset-4',
    assetName: 'Compressor Unit #2',
    severity: 'high',
    title: 'Abnormal Vibration Detected',
    description: 'Vibration levels at 4.8 mm/s, indicating potential bearing failure.',
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    acknowledged: false,
  },
  {
    id: 'alert-3',
    assetId: 'asset-2',
    assetName: 'CNC Mill #3',
    severity: 'medium',
    title: 'Elevated Temperature Trend',
    description: 'Temperature trending upward over past 6 hours. Monitor closely.',
    timestamp: new Date(Date.now() - 1000 * 60 * 120),
    acknowledged: false,
  },
  {
    id: 'alert-4',
    assetId: 'asset-6',
    assetName: 'Paint Booth #1',
    severity: 'high',
    title: 'Equipment Offline',
    description: 'No telemetry received for 45 minutes. Connection lost.',
    timestamp: new Date(Date.now() - 1000 * 60 * 47),
    acknowledged: false,
  },
  {
    id: 'alert-5',
    assetId: 'asset-2',
    assetName: 'CNC Mill #3',
    severity: 'low',
    title: 'Maintenance Window Approaching',
    description: 'Scheduled maintenance due in 30 days.',
    timestamp: new Date(Date.now() - 1000 * 60 * 180),
    acknowledged: true,
  },
];

export const mockKPIs: KPI[] = [
  { label: 'Overall Uptime', value: '94.8%', change: 2.3, trend: 'up' },
  { label: 'MTBF', value: '847 hrs', change: 5.1, trend: 'up' },
  { label: 'MTTR', value: '2.4 hrs', change: -12.5, trend: 'up' },
  { label: 'Active Alerts', value: '11', change: 15.8, trend: 'down' },
  { label: 'Assets at Risk', value: '2', change: -33.3, trend: 'up' },
  { label: 'Energy Efficiency', value: '87.2%', change: 1.8, trend: 'up' },
];
