import { Prescription, WorkflowExecution, PrescriptionFeedback, CMMSAdapter, PrescriptionMetrics } from "@/types/prescriptions";

export const mockPrescriptions: Prescription[] = [
  {
    id: "presc-1",
    title: "Bearing Replacement - Motor 3-Phase",
    description: "Complete procedure for replacing worn bearings in 3-phase induction motors with safety protocols",
    status: "approved",
    source: "expert",
    assetType: "Motor",
    category: "Mechanical",
    createdBy: "John Smith (Senior Technician)",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
    requiresApproval: true,
    approvedBy: "Sarah Johnson (Plant Manager)",
    approvedAt: new Date("2024-01-20"),
    effectivenessRating: 4.7,
    usageCount: 24,
    successRate: 95.8,
    estimatedDuration: 120,
    cmmsLinked: ["SAP PM", "ServiceNow"],
    steps: [
      {
        id: "step-1",
        order: 1,
        description: "Lockout/Tagout procedure - Isolate electrical supply",
        expectedTime: 15,
        tools: ["Lockout kit", "Multimeter"],
        safety: ["PPE required", "Verify zero energy", "Post warning signs"],
        parts: [],
      },
      {
        id: "step-2",
        order: 2,
        description: "Remove motor covers and access bearing housings",
        expectedTime: 20,
        tools: ["Socket set", "Screwdrivers", "Cleaning cloths"],
        safety: ["Wear gloves", "Eye protection"],
        parts: [],
      },
      {
        id: "step-3",
        order: 3,
        description: "Extract old bearings using bearing puller",
        expectedTime: 30,
        tools: ["Bearing puller", "Soft mallet", "Heat gun"],
        safety: ["Hearing protection if hammering"],
        parts: [],
      },
      {
        id: "step-4",
        order: 4,
        description: "Clean bearing seats and inspect for damage",
        expectedTime: 15,
        tools: ["Wire brush", "Cleaning solvent", "Inspection mirror"],
        safety: ["Ventilation required for solvents"],
        parts: [],
      },
      {
        id: "step-5",
        order: 5,
        description: "Install new bearings with proper alignment",
        expectedTime: 25,
        tools: ["Bearing press", "Alignment tools", "Torque wrench"],
        safety: ["Follow torque specifications"],
        parts: ["SKF 6309-2RS bearings (2x)", "High-temp grease"],
      },
      {
        id: "step-6",
        order: 6,
        description: "Reassemble motor and verify rotation",
        expectedTime: 15,
        tools: ["Socket set", "Rotation tester"],
        safety: ["Check for binding before energizing"],
        parts: [],
      },
    ],
  },
  {
    id: "presc-2",
    title: "Vibration Anomaly Investigation",
    description: "AI-generated diagnostic protocol for investigating elevated vibration readings",
    status: "active",
    source: "ai-generated",
    assetType: "Pump",
    category: "Diagnostics",
    createdBy: "AI Diagnostic Engine",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
    requiresApproval: false,
    effectivenessRating: 4.3,
    usageCount: 12,
    successRate: 91.7,
    estimatedDuration: 45,
    cmmsLinked: ["IBM Maximo"],
    steps: [
      {
        id: "step-1",
        order: 1,
        description: "Collect baseline vibration data at multiple points",
        expectedTime: 10,
        tools: ["Vibration analyzer", "Data logger"],
        safety: ["Maintain safe distance from rotating equipment"],
        parts: [],
      },
      {
        id: "step-2",
        order: 2,
        description: "Perform spectral analysis to identify frequency patterns",
        expectedTime: 15,
        tools: ["Spectrum analyzer software"],
        safety: [],
        parts: [],
      },
      {
        id: "step-3",
        order: 3,
        description: "Check for loose mounting bolts and foundation issues",
        expectedTime: 10,
        tools: ["Torque wrench", "Level"],
        safety: ["Ensure equipment is stopped"],
        parts: [],
      },
      {
        id: "step-4",
        order: 4,
        description: "Inspect coupling alignment",
        expectedTime: 10,
        tools: ["Alignment laser", "Dial indicator"],
        safety: [],
        parts: [],
      },
    ],
  },
  {
    id: "presc-3",
    title: "Thermal Imaging Inspection Protocol",
    description: "Expert-validated thermal survey procedure for electrical distribution",
    status: "approved",
    source: "hybrid",
    assetType: "Electrical Panel",
    category: "Electrical",
    createdBy: "AI Engine + Mike Rodriguez (Electrician)",
    createdAt: new Date("2024-01-28"),
    updatedAt: new Date("2024-02-05"),
    requiresApproval: true,
    approvedBy: "Lisa Chen (Electrical Lead)",
    approvedAt: new Date("2024-02-05"),
    effectivenessRating: 4.9,
    usageCount: 18,
    successRate: 100,
    estimatedDuration: 60,
    cmmsLinked: ["ServiceNow", "MaintainX"],
    steps: [
      {
        id: "step-1",
        order: 1,
        description: "Pre-inspection safety briefing and panel assessment",
        expectedTime: 10,
        tools: ["Thermal camera", "PPE kit"],
        safety: ["Arc flash rated PPE", "Insulated tools", "Safety observer required"],
        parts: [],
      },
      {
        id: "step-2",
        order: 2,
        description: "Capture thermal images of all connections under load",
        expectedTime: 25,
        tools: ["FLIR thermal camera", "Data tablet"],
        safety: ["Maintain safe distance", "No contact with live parts"],
        parts: [],
      },
      {
        id: "step-3",
        order: 3,
        description: "Document hot spots exceeding 15°C delta",
        expectedTime: 15,
        tools: ["Tablet with annotation software"],
        safety: [],
        parts: [],
      },
      {
        id: "step-4",
        order: 4,
        description: "Generate priority list for remediation",
        expectedTime: 10,
        tools: ["Report generator"],
        safety: [],
        parts: [],
      },
    ],
  },
];

export const mockWorkflowExecutions: WorkflowExecution[] = [
  {
    id: "wf-1",
    prescriptionId: "presc-1",
    prescriptionTitle: "Bearing Replacement - Motor 3-Phase",
    assetId: "asset-1",
    assetName: "Turbine A1",
    status: "in-progress",
    startedAt: new Date("2024-02-10T08:30:00"),
    executedBy: "Tom Wilson",
    currentStep: 3,
    totalSteps: 6,
    syncedToCMMS: true,
    cmmsWorkOrderId: "WO-2024-1245",
  },
  {
    id: "wf-2",
    prescriptionId: "presc-2",
    prescriptionTitle: "Vibration Anomaly Investigation",
    assetId: "asset-3",
    assetName: "Pump C2",
    status: "completed",
    startedAt: new Date("2024-02-09T14:00:00"),
    completedAt: new Date("2024-02-09T14:42:00"),
    executedBy: "Alex Martinez",
    currentStep: 4,
    totalSteps: 4,
    feedbackRating: 4,
    feedbackNotes: "Protocol was clear and effective. Found misalignment issue.",
    syncedToCMMS: true,
    cmmsWorkOrderId: "WO-2024-1238",
  },
  {
    id: "wf-3",
    prescriptionId: "presc-3",
    prescriptionTitle: "Thermal Imaging Inspection Protocol",
    assetId: "asset-5",
    assetName: "Panel 3B",
    status: "pending",
    startedAt: new Date("2024-02-11T09:00:00"),
    executedBy: "Rachel Kim",
    currentStep: 0,
    totalSteps: 4,
    syncedToCMMS: false,
  },
];

export const mockFeedback: PrescriptionFeedback[] = [
  {
    id: "fb-1",
    prescriptionId: "presc-1",
    workflowId: "wf-2",
    technicianId: "tech-1",
    technicianName: "Tom Wilson",
    rating: 5,
    effectiveness: 5,
    clarity: 4,
    notes: "Very detailed and easy to follow. Saved significant time.",
    suggestedImprovements: "Add photo references for bearing orientation",
    createdAt: new Date("2024-02-08"),
  },
  {
    id: "fb-2",
    prescriptionId: "presc-2",
    workflowId: "wf-2",
    technicianId: "tech-2",
    technicianName: "Alex Martinez",
    rating: 4,
    effectiveness: 4,
    clarity: 5,
    notes: "AI protocol was accurate. Helped identify root cause quickly.",
    suggestedImprovements: "Include more context on interpreting spectrum patterns",
    createdAt: new Date("2024-02-09"),
  },
];

export const mockCMMSAdapters: CMMSAdapter[] = [
  {
    system: "SAP PM",
    connected: true,
    lastSync: new Date("2024-02-10T10:30:00"),
    workOrdersSynced: 145,
    status: "active",
  },
  {
    system: "ServiceNow",
    connected: true,
    lastSync: new Date("2024-02-10T10:28:00"),
    workOrdersSynced: 89,
    status: "active",
  },
  {
    system: "IBM Maximo",
    connected: true,
    lastSync: new Date("2024-02-10T10:25:00"),
    workOrdersSynced: 67,
    status: "active",
  },
  {
    system: "MaintainX",
    connected: false,
    status: "disconnected",
    workOrdersSynced: 0,
  },
];

export const mockPrescriptionMetrics: PrescriptionMetrics = {
  totalPrescriptions: 24,
  activeWorkflows: 7,
  completedWorkflows: 156,
  averageEffectivenessRating: 4.5,
  adoptionRate: 87.3,
  successRate: 94.2,
  averageCompletionTime: 78,
  cmmsIntegrations: 3,
};
