import { Sensor, Gateway, SensorMetrics } from "@/types/sensors";

export const mockSensors: Sensor[] = [
  {
    id: "sensor-1",
    name: "Bearing Temperature Sensor",
    type: "temperature",
    status: "online",
    deviceId: "TEMP-001-4A3B",
    location: {
      assetId: "asset-1",
      assetName: "Turbine A1",
      component: "Bearing Housing - Drive End",
      coordinates: { x: 120, y: 45, z: 85 },
    },
    configuration: {
      samplingFrequency: 10,
      reportingInterval: 5,
      engineeringUnit: "°C",
      minValue: -40,
      maxValue: 200,
      accuracy: 0.1,
      calibrationDate: new Date("2024-01-15"),
      nextCalibrationDate: new Date("2025-01-15"),
    },
    connectivity: {
      gatewayId: "gw-1",
      protocol: "MQTT",
      address: "sensors/turbine-a1/bearing/temp",
      lastSeen: new Date(),
      signalStrength: 92,
      batteryLevel: 78,
      firmwareVersion: "v2.4.1",
    },
    dataMapping: {
      tagName: "TRB_A1_BRG_TEMP",
      description: "Turbine A1 Bearing Temperature",
      resamplingRule: "average",
      alertThresholdHigh: 85,
      alertThresholdLow: 10,
    },
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date(),
  },
  {
    id: "sensor-2",
    name: "Vibration Accelerometer",
    type: "vibration",
    status: "online",
    deviceId: "VIB-002-8F9E",
    location: {
      assetId: "asset-1",
      assetName: "Turbine A1",
      component: "Motor Housing - Vertical",
    },
    configuration: {
      samplingFrequency: 1000,
      reportingInterval: 1,
      engineeringUnit: "g",
      minValue: 0,
      maxValue: 50,
      accuracy: 0.01,
      calibrationDate: new Date("2024-02-01"),
      nextCalibrationDate: new Date("2025-02-01"),
    },
    connectivity: {
      gatewayId: "gw-1",
      protocol: "OPC UA",
      address: "ns=2;s=Turbine.A1.Vibration",
      lastSeen: new Date(),
      signalStrength: 95,
      firmwareVersion: "v3.1.0",
    },
    dataMapping: {
      tagName: "TRB_A1_VIB_RMS",
      description: "Turbine A1 Vibration RMS",
      resamplingRule: "max",
      alertThresholdHigh: 10,
    },
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date(),
  },
  {
    id: "sensor-3",
    name: "Discharge Pressure Sensor",
    type: "pressure",
    status: "warning",
    deviceId: "PRES-003-2C1D",
    location: {
      assetId: "asset-3",
      assetName: "Pump C2",
      component: "Discharge Line",
    },
    configuration: {
      samplingFrequency: 5,
      reportingInterval: 10,
      engineeringUnit: "PSI",
      minValue: 0,
      maxValue: 500,
      accuracy: 0.5,
      calibrationDate: new Date("2023-11-20"),
      nextCalibrationDate: new Date("2024-11-20"),
    },
    connectivity: {
      gatewayId: "gw-2",
      protocol: "Modbus TCP",
      address: "40001",
      lastSeen: new Date(Date.now() - 300000),
      signalStrength: 68,
      batteryLevel: 22,
      firmwareVersion: "v1.8.2",
    },
    dataMapping: {
      tagName: "PMP_C2_DISCH_PRES",
      description: "Pump C2 Discharge Pressure",
      resamplingRule: "average",
      alertThresholdHigh: 450,
      alertThresholdLow: 50,
    },
    createdAt: new Date("2023-11-20"),
    updatedAt: new Date(),
  },
  {
    id: "sensor-4",
    name: "Energy Meter - Main Panel",
    type: "energy",
    status: "online",
    deviceId: "PWR-004-7B5A",
    location: {
      assetId: "asset-5",
      assetName: "Panel 3B",
      component: "Main Breaker",
    },
    configuration: {
      samplingFrequency: 1,
      reportingInterval: 60,
      engineeringUnit: "kWh",
      minValue: 0,
      maxValue: 10000,
      accuracy: 1,
      calibrationDate: new Date("2024-01-10"),
      nextCalibrationDate: new Date("2025-01-10"),
    },
    connectivity: {
      gatewayId: "gw-3",
      protocol: "Modbus RTU",
      address: "30001",
      lastSeen: new Date(),
      signalStrength: 88,
      firmwareVersion: "v4.2.0",
    },
    dataMapping: {
      tagName: "PNL_3B_ENERGY_TOTAL",
      description: "Panel 3B Total Energy Consumption",
      resamplingRule: "sum",
    },
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date(),
  },
  {
    id: "sensor-5",
    name: "Acoustic Sensor - Bearing Monitor",
    type: "acoustic",
    status: "offline",
    deviceId: "ACS-005-9D2F",
    location: {
      assetId: "asset-2",
      assetName: "Compressor B1",
      component: "Thrust Bearing",
    },
    configuration: {
      samplingFrequency: 500,
      reportingInterval: 5,
      engineeringUnit: "dB",
      minValue: 20,
      maxValue: 120,
      accuracy: 0.5,
      calibrationDate: new Date("2024-01-05"),
      nextCalibrationDate: new Date("2025-01-05"),
    },
    connectivity: {
      gatewayId: "gw-2",
      protocol: "MQTT",
      address: "sensors/compressor-b1/acoustic",
      lastSeen: new Date(Date.now() - 3600000),
      signalStrength: 0,
      batteryLevel: 0,
      firmwareVersion: "v2.1.3",
    },
    dataMapping: {
      tagName: "CMP_B1_ACOUSTIC_DB",
      description: "Compressor B1 Acoustic Level",
      resamplingRule: "max",
      alertThresholdHigh: 95,
    },
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date(),
  },
];

export const mockGateways: Gateway[] = [
  {
    id: "gw-1",
    name: "Edge Gateway - Building A",
    protocol: "MQTT",
    status: "healthy",
    ipAddress: "192.168.1.100",
    port: 1883,
    configuration: {
      mqttTopics: [
        "sensors/turbine-a1/#",
        "sensors/motor-a2/#",
        "sensors/building-a/#",
      ],
      opcuaNodes: [
        "ns=2;s=Turbine.A1.Vibration",
        "ns=2;s=Motor.A2.Current",
      ],
    },
    health: {
      cpuUsage: 34,
      memoryUsage: 52,
      diskUsage: 28,
      networkLatency: 12,
      bufferUsage: 15,
      bufferedMessages: 245,
      uptime: 720,
    },
    connectedSensors: 12,
    lastSeen: new Date(),
    firmwareVersion: "v5.2.1",
    location: "Building A - Control Room",
  },
  {
    id: "gw-2",
    name: "Edge Gateway - Pump House",
    protocol: "Modbus TCP",
    status: "degraded",
    ipAddress: "192.168.1.101",
    port: 502,
    configuration: {
      modbusMapping: [
        {
          register: 40001,
          function: "Read Holding Register",
          dataType: "Float32",
          tagName: "PMP_C2_DISCH_PRES",
          scaleFactor: 0.1,
        },
        {
          register: 40003,
          function: "Read Holding Register",
          dataType: "Float32",
          tagName: "PMP_C2_FLOW_RATE",
        },
      ],
    },
    health: {
      cpuUsage: 68,
      memoryUsage: 78,
      diskUsage: 45,
      networkLatency: 85,
      bufferUsage: 62,
      bufferedMessages: 1820,
      uptime: 168,
    },
    connectedSensors: 8,
    lastSeen: new Date(Date.now() - 120000),
    firmwareVersion: "v5.1.8",
    location: "Pump House - Field Cabinet",
  },
  {
    id: "gw-3",
    name: "Edge Gateway - Electrical Room",
    protocol: "Modbus RTU",
    status: "healthy",
    ipAddress: "192.168.1.102",
    port: 502,
    configuration: {
      modbusMapping: [
        {
          register: 30001,
          function: "Read Input Register",
          dataType: "Uint32",
          tagName: "PNL_3B_ENERGY_TOTAL",
        },
        {
          register: 30005,
          function: "Read Input Register",
          dataType: "Float32",
          tagName: "PNL_3B_POWER_FACTOR",
        },
      ],
    },
    health: {
      cpuUsage: 22,
      memoryUsage: 38,
      diskUsage: 18,
      networkLatency: 8,
      bufferUsage: 5,
      bufferedMessages: 82,
      uptime: 2160,
    },
    connectedSensors: 15,
    lastSeen: new Date(),
    firmwareVersion: "v5.2.1",
    location: "Electrical Room - Main Distribution",
  },
];

export const mockSensorMetrics: SensorMetrics = {
  totalSensors: 35,
  onlineSensors: 28,
  offlineSensors: 3,
  warningSensors: 4,
  activeGateways: 3,
  totalDataPoints: 1247893,
  averageLatency: 18,
};
